###
# sets up and configures Supervisor to run the WSGI server
##

- name: ensure Supervisor is installed
  apt: name=supervisor state=present update_cache=yes
  become: true


- name: create Supervisor configuration
  template: src=supervisor_app.conf.j2
            dest=/etc/supervisor/conf.d/{{ app_name }}.conf
  become: true


- name: stop supervisor
  service: name=supervisor state=stopped
  become: true


- name: pause for restart to take effect
  pause: seconds=2


- name: start Supervisor back up
  service: name=supervisor state=started
  become: true
  notify:
    - restart nginx

